name: Android build & upload

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:  
  build_apk:
    permissions: write-all
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
        java-package: jdk
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: "stable"
    
    - name: Get dependencies
      run: flutter pub get

    - name: Build Android App Bundle
      run: flutter build apk --release --split-per-abi --info

    - name: Sign app APK
      id: sign_app
      uses: ilharp/sign-android-release@nightly
      with:
        releaseDir: build/app/outputs/apk/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
    - name: Upload APK
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        name: Catsuka ${{ github.ref_name }}
        tag: ${{ github.ref_name }}
        artifacts: build/app/outputs/apk/release/*.apk
        replacesArtifacts: true
        allowUpdates: true
